### ISSUE TITLE
better textures?

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-wool#5]
The wool doesnt look very wooly.. haha

**Comment by deathcap** [comment]
The textures aren't in this plugin, but handled by whatever texture pack is currently loaded, others provide better textures, from the reamde:

> Note: this screenshot was taken with ProgrammerArt v2.0, but for better textures you can use other resource packs, which voxel-wool is compatible with; for example Faithful32:

![screenshot](https://camo.githubusercontent.com/19dedcc111b510b27540082be9df898407569caf/687474703a2f2f692e696d6775722e636f6d2f62736b4d506d772e706e67)
